export type Ingredient = {
  readonly name: string;
  readonly aliases?: readonly string[];
};

/**
 * Order is load-bearing: uFuzzy breaks equal-scoring ties by haystack position,
 * so this list runs roughly most-common first. Typing "ch" should surface
 * chicken before chayote.
 *
 * Aliases exist for the cases fuzzy matching structurally cannot reach —
 * "coriander" and "cilantro" share almost no characters. Regional names and
 * common synonyms belong here; misspellings do not (the phonetic pass covers
 * those). Grow this from the miss log rather than by guessing.
 */
export const INGREDIENTS: readonly Ingredient[] = [
  // Aromatics and everyday vegetables
  { name: "onion", aliases: ["yellow onion", "brown onion"] },
  { name: "garlic" },
  { name: "tomato" },
  { name: "potato" },
  { name: "carrot" },
  { name: "bell pepper", aliases: ["capsicum", "sweet pepper"] },
  { name: "celery" },
  { name: "mushroom" },
  { name: "spinach" },
  { name: "broccoli" },
  { name: "cucumber" },
  { name: "zucchini", aliases: ["courgette"] },
  { name: "lettuce" },
  { name: "cabbage" },
  { name: "cauliflower" },
  { name: "green bean", aliases: ["string bean", "french bean"] },
  { name: "corn", aliases: ["sweetcorn", "maize"] },
  { name: "pea", aliases: ["green pea", "garden pea"] },
  { name: "sweet potato", aliases: ["yam", "kumara"] },
  { name: "kale" },
  { name: "asparagus" },
  { name: "eggplant", aliases: ["aubergine", "brinjal"] },
  { name: "scallion", aliases: ["green onion", "spring onion"] },
  { name: "shallot" },
  { name: "leek" },
  { name: "red onion" },
  { name: "brussels sprout" },
  { name: "beet", aliases: ["beetroot"] },
  { name: "radish" },
  { name: "butternut squash" },
  { name: "pumpkin" },
  { name: "arugula", aliases: ["rocket", "roquette"] },
  { name: "romaine lettuce", aliases: ["cos lettuce"] },
  { name: "swiss chard", aliases: ["chard", "silverbeet"] },
  { name: "bok choy", aliases: ["pak choi", "chinese cabbage"] },
  { name: "artichoke" },
  { name: "okra", aliases: ["ladies fingers"] },
  { name: "turnip" },
  { name: "parsnip" },
  { name: "rutabaga", aliases: ["swede"] },
  { name: "snow pea", aliases: ["mangetout"] },
  { name: "sugar snap pea" },
  { name: "fennel" },
  { name: "endive", aliases: ["chicory"] },
  { name: "watercress" },
  { name: "bean sprout" },
  { name: "water chestnut" },
  { name: "jalapeno", aliases: ["jalapeño"] },
  { name: "serrano pepper" },
  { name: "poblano pepper" },
  { name: "chili pepper", aliases: ["chile", "chilli", "hot pepper"] },
  { name: "habanero" },
  { name: "cherry tomato" },
  { name: "sun dried tomato" },
  { name: "roasted red pepper" },

  // Proteins
  { name: "chicken breast" },
  { name: "chicken thigh" },
  { name: "chicken" },
  {
    name: "ground beef",
    aliases: ["beef mince", "minced beef", "hamburger meat"],
  },
  { name: "beef" },
  { name: "steak" },
  { name: "pork" },
  { name: "pork chop" },
  { name: "ground pork", aliases: ["pork mince", "minced pork"] },
  { name: "bacon" },
  { name: "sausage" },
  { name: "egg" },
  { name: "salmon" },
  { name: "tuna" },
  { name: "shrimp", aliases: ["prawn"] },
  { name: "turkey" },
  { name: "ground turkey", aliases: ["turkey mince", "minced turkey"] },
  { name: "ham" },
  { name: "tofu", aliases: ["bean curd"] },
  { name: "cod" },
  { name: "tilapia" },
  { name: "lamb" },
  { name: "ground lamb", aliases: ["lamb mince", "minced lamb"] },
  { name: "chorizo" },
  { name: "pancetta" },
  { name: "prosciutto", aliases: ["parma ham"] },
  { name: "salami" },
  { name: "pepperoni" },
  { name: "anchovy" },
  { name: "sardine" },
  { name: "crab" },
  { name: "scallop" },
  { name: "mussel" },
  { name: "clam" },
  { name: "squid", aliases: ["calamari"] },
  { name: "halibut" },
  { name: "trout" },
  { name: "sea bass" },
  { name: "duck" },
  { name: "veal" },
  { name: "brisket" },
  { name: "pork belly" },
  { name: "chicken wing" },
  { name: "chicken stock", aliases: ["chicken broth"] },
  { name: "beef stock", aliases: ["beef broth"] },
  { name: "vegetable stock", aliases: ["vegetable broth"] },
  { name: "tempeh" },
  { name: "seitan" },

  // Dairy and eggs
  { name: "butter" },
  { name: "milk" },
  { name: "cheddar cheese" },
  { name: "parmesan cheese", aliases: ["parmigiano reggiano", "parmesan"] },
  { name: "mozzarella cheese", aliases: ["mozzarella"] },
  { name: "cream cheese" },
  { name: "sour cream" },
  {
    name: "heavy cream",
    aliases: ["double cream", "whipping cream", "heavy whipping cream"],
  },
  { name: "yogurt", aliases: ["yoghurt"] },
  { name: "greek yogurt", aliases: ["greek yoghurt"] },
  { name: "feta cheese", aliases: ["feta"] },
  { name: "ricotta cheese", aliases: ["ricotta"] },
  { name: "goat cheese", aliases: ["chevre"] },
  { name: "cottage cheese" },
  { name: "cream", aliases: ["single cream"] },
  { name: "half and half" },
  { name: "buttermilk" },
  { name: "gruyere cheese", aliases: ["gruyere"] },
  { name: "blue cheese", aliases: ["gorgonzola", "stilton", "roquefort"] },
  { name: "swiss cheese", aliases: ["emmental"] },
  { name: "provolone cheese" },
  { name: "monterey jack cheese" },
  { name: "mascarpone" },
  { name: "creme fraiche" },
  { name: "condensed milk" },
  { name: "evaporated milk" },
  { name: "almond milk" },
  { name: "oat milk" },
  { name: "coconut milk" },
  { name: "ghee", aliases: ["clarified butter"] },

  // Pantry staples
  { name: "olive oil", aliases: ["extra virgin olive oil"] },
  { name: "salt", aliases: ["sea salt", "kosher salt", "table salt"] },
  { name: "black pepper", aliases: ["pepper", "cracked pepper"] },
  {
    name: "flour",
    aliases: ["all purpose flour", "plain flour", "white flour"],
  },
  {
    name: "sugar",
    aliases: ["granulated sugar", "white sugar", "caster sugar"],
  },
  { name: "brown sugar", aliases: ["light brown sugar", "dark brown sugar"] },
  { name: "rice", aliases: ["white rice", "long grain rice"] },
  { name: "pasta" },
  { name: "bread" },
  {
    name: "vegetable oil",
    aliases: ["canola oil", "rapeseed oil", "sunflower oil"],
  },
  { name: "baking powder" },
  {
    name: "baking soda",
    aliases: ["bicarbonate of soda", "bicarb", "sodium bicarbonate"],
  },
  { name: "vanilla extract", aliases: ["vanilla", "vanilla essence"] },
  { name: "honey" },
  { name: "maple syrup" },
  { name: "soy sauce", aliases: ["shoyu", "light soy sauce"] },
  { name: "vinegar", aliases: ["white vinegar", "distilled vinegar"] },
  { name: "balsamic vinegar" },
  { name: "apple cider vinegar", aliases: ["cider vinegar"] },
  { name: "red wine vinegar" },
  { name: "rice vinegar", aliases: ["rice wine vinegar"] },
  { name: "ketchup", aliases: ["tomato ketchup", "tomato sauce"] },
  { name: "mustard", aliases: ["yellow mustard"] },
  { name: "dijon mustard" },
  { name: "wholegrain mustard" },
  { name: "mayonnaise", aliases: ["mayo"] },
  { name: "hot sauce", aliases: ["tabasco", "sriracha"] },
  { name: "worcestershire sauce" },
  { name: "sesame oil", aliases: ["toasted sesame oil"] },
  { name: "coconut oil" },
  { name: "canned tomato", aliases: ["tinned tomato", "plum tomato"] },
  { name: "tomato paste", aliases: ["tomato puree", "tomato concentrate"] },
  { name: "tomato sauce", aliases: ["passata"] },
  { name: "peanut butter" },
  { name: "breadcrumb", aliases: ["panko", "bread crumbs"] },
  { name: "cornstarch", aliases: ["cornflour", "corn starch"] },
  { name: "oat", aliases: ["rolled oats", "porridge oats", "oatmeal"] },
  { name: "quinoa" },
  { name: "lentil", aliases: ["red lentil", "green lentil", "puy lentil"] },
  { name: "chickpea", aliases: ["garbanzo bean", "garbanzo"] },
  { name: "black bean" },
  { name: "kidney bean" },
  { name: "cannellini bean", aliases: ["white bean"] },
  { name: "pinto bean" },
  { name: "butter bean", aliases: ["lima bean"] },
  { name: "couscous" },
  { name: "noodle", aliases: ["egg noodle"] },
  { name: "rice noodle" },
  { name: "tortilla" },
  { name: "spaghetti" },
  { name: "penne" },
  { name: "lasagna", aliases: ["lasagne"] },
  { name: "brown rice" },
  { name: "basmati rice" },
  { name: "arborio rice", aliases: ["risotto rice"] },
  { name: "jasmine rice" },
  { name: "barley", aliases: ["pearl barley"] },
  { name: "bulgur", aliases: ["bulgur wheat", "cracked wheat"] },
  { name: "polenta", aliases: ["cornmeal"] },
  { name: "bread flour", aliases: ["strong flour"] },
  { name: "self raising flour", aliases: ["self rising flour"] },
  { name: "powdered sugar", aliases: ["icing sugar", "confectioners sugar"] },
  { name: "yeast", aliases: ["active dry yeast", "instant yeast"] },
  { name: "cocoa powder", aliases: ["cacao powder"] },
  { name: "chocolate", aliases: ["dark chocolate", "chocolate chips"] },
  { name: "molasses", aliases: ["treacle", "black treacle"] },
  { name: "golden syrup" },
  { name: "cornflake" },
  { name: "gelatin", aliases: ["gelatine"] },
  { name: "fish sauce", aliases: ["nam pla"] },
  { name: "oyster sauce" },
  { name: "hoisin sauce" },
  { name: "miso", aliases: ["miso paste"] },
  { name: "tahini", aliases: ["sesame paste"] },
  { name: "harissa" },
  { name: "gochujang", aliases: ["korean chili paste"] },
  { name: "curry paste", aliases: ["red curry paste", "green curry paste"] },
  { name: "pesto" },
  { name: "salsa" },
  { name: "olive", aliases: ["kalamata olive", "green olive"] },
  { name: "caper" },
  { name: "pickle", aliases: ["gherkin", "cornichon"] },
  { name: "horseradish" },
  { name: "wine", aliases: ["white wine", "red wine", "cooking wine"] },
  { name: "beer" },
  { name: "mirin" },
  { name: "sake" },

  // Herbs
  { name: "basil" },
  { name: "parsley", aliases: ["flat leaf parsley", "italian parsley"] },
  { name: "cilantro", aliases: ["coriander", "chinese parsley"] },
  { name: "thyme" },
  { name: "rosemary" },
  { name: "oregano" },
  { name: "mint" },
  { name: "dill" },
  { name: "sage" },
  { name: "chive" },
  { name: "bay leaf" },
  { name: "tarragon" },
  { name: "lemongrass" },
  { name: "kaffir lime leaf", aliases: ["makrut lime leaf"] },
  { name: "curry leaf" },

  // Spices
  { name: "paprika", aliases: ["sweet paprika"] },
  { name: "smoked paprika" },
  { name: "cumin", aliases: ["ground cumin", "cumin seed"] },
  { name: "chili powder", aliases: ["chilli powder"] },
  { name: "cinnamon", aliases: ["ground cinnamon", "cinnamon stick"] },
  { name: "garlic powder", aliases: ["granulated garlic"] },
  { name: "onion powder" },
  { name: "turmeric" },
  { name: "ginger", aliases: ["ground ginger", "root ginger"] },
  { name: "nutmeg" },
  { name: "cayenne pepper", aliases: ["cayenne"] },
  { name: "coriander seed", aliases: ["ground coriander"] },
  { name: "cardamom" },
  { name: "clove" },
  { name: "curry powder" },
  { name: "red pepper flake", aliases: ["chili flakes", "crushed red pepper"] },
  { name: "allspice" },
  { name: "saffron" },
  { name: "star anise" },
  { name: "fennel seed" },
  { name: "mustard seed" },
  { name: "caraway seed" },
  { name: "juniper berry" },
  { name: "sumac" },
  { name: "za atar", aliases: ["zaatar", "za'atar"] },
  { name: "garam masala" },
  { name: "five spice", aliases: ["chinese five spice"] },
  { name: "old bay seasoning" },
  { name: "italian seasoning", aliases: ["mixed herbs"] },
  { name: "vanilla bean", aliases: ["vanilla pod"] },
  { name: "peppercorn", aliases: ["black peppercorn"] },
  { name: "white pepper" },

  // Fruit
  { name: "lemon" },
  { name: "lime" },
  { name: "apple" },
  { name: "banana" },
  { name: "orange" },
  { name: "avocado" },
  { name: "strawberry" },
  { name: "blueberry" },
  { name: "raspberry" },
  { name: "blackberry" },
  { name: "grape" },
  { name: "pineapple" },
  { name: "mango" },
  { name: "peach" },
  { name: "pear" },
  { name: "watermelon" },
  { name: "cherry" },
  { name: "cranberry" },
  { name: "coconut", aliases: ["shredded coconut", "desiccated coconut"] },
  { name: "date", aliases: ["medjool date"] },
  { name: "fig" },
  { name: "plum" },
  { name: "apricot" },
  { name: "pomegranate" },
  { name: "kiwi", aliases: ["kiwifruit"] },
  { name: "grapefruit" },
  { name: "raisin", aliases: ["sultana", "golden raisin"] },
  { name: "prune", aliases: ["dried plum"] },
  { name: "cantaloupe", aliases: ["melon", "rockmelon"] },
  { name: "nectarine" },
  { name: "papaya" },
  { name: "passion fruit" },
  { name: "rhubarb" },
  { name: "plantain" },

  // Nuts and seeds
  { name: "almond", aliases: ["flaked almonds", "ground almonds"] },
  { name: "walnut" },
  { name: "pecan" },
  { name: "cashew" },
  { name: "peanut", aliases: ["groundnut"] },
  { name: "pistachio" },
  { name: "hazelnut", aliases: ["filbert"] },
  { name: "pine nut", aliases: ["pignoli"] },
  { name: "macadamia" },
  { name: "sesame seed" },
  { name: "sunflower seed" },
  { name: "pumpkin seed", aliases: ["pepita"] },
  { name: "chia seed" },
  { name: "flaxseed", aliases: ["linseed", "flax seed"] },
  { name: "poppy seed" },
];
