/**
 * Hand-written types for the `spoonacular` package.
 *
 * The official SDK (published by Spoonacular's own maintainer) is generated by
 * OpenAPI Generator's JavaScript target: CommonJS, callback-based, and it ships
 * NO type declarations — and there is no @types/spoonacular. Without this file
 * every import from it is an implicit `any`.
 *
 * Response payloads are deliberately typed `unknown`: the SDK's own generated
 * models aren't typed either, and we validate every response with zod in
 * src/sources/spoonacular.ts. zod is the real type boundary — this shim only
 * needs to describe the call surface.
 *
 * Only the members we actually use are declared. Add more as needed.
 */
declare module "spoonacular" {
  /** OpenAPI-generator callback: (error, data, rawResponse). */
  export type SpoonacularCallback = (
    error: (Error & { status?: number }) | null,
    data: unknown,
    response: unknown,
  ) => void;

  export interface ApiKeyAuthentication {
    type: string;
    in: string;
    name: string;
    apiKey?: string;
  }

  export class ApiClient {
    constructor(basePath?: string);
    static instance: ApiClient;
    basePath: string;
    timeout: number;
    authentications: { apiKeyScheme: ApiKeyAuthentication };
  }

  export class RecipesApi {
    constructor(apiClient?: ApiClient);

    searchRecipesByIngredients(
      ingredients: string,
      opts: {
        number?: number;
        ranking?: number;
        ignorePantry?: boolean;
      },
      callback: SpoonacularCallback,
    ): unknown;

    getRecipeInformation(
      id: number,
      opts: { includeNutrition?: boolean },
      callback: SpoonacularCallback,
    ): unknown;
  }
}
